### ISSUE TITLE
Batch modify branch indexing schemes

### ISSUE THREAD

**Issue by mdavoodi** [mohamicorp/search-for-stash-issues#16]
Currently the default branch indexing scheme can be configured on a repository level, but for large organizations it's difficult to configure this scheme for each individual repository. 

There should be an easy way to configure the indexing schemes on either a project or global level.

**Comment by alston-rousseau** [comment]
Agreed. This would be very nice. Thanks! This tool is great

**Comment by mdavoodi** [comment]
This is now done on version [2.7](https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.search-for-stash/server/versionhistory) on a global level. I've made a new issue for project level #32.
