### ISSUE TITLE
Branch regex doesn't seem to work in all cases

### ISSUE THREAD

**Issue by kavehv** [mohamicorp/search-for-stash-issues#17]
Using something like `HEAD|(refs\/heads\/(master|develop|[0-9\.]+@RELEASES))` doesn't seem to pick up a branch like `refs/heads/0.1@RELEASES`

**Comment by mdavoodi** [comment]
Working on reproducing.

**Comment by mdavoodi** [comment]
Looks like this was a bug in the re-indexing process for an internal node of elasticsearch. We've released the fix for it. See here:

https://marketplace.atlassian.com/plugins/com.mohamicorp.stash.search-for-stash/server/versionhistory

Let me know if that doesn't fix your issue.

**Comment by mdavoodi** [comment]
Closing the issue.
