### ISSUE TITLE
Smarter Search Addon not worked with Bitbucket Server last Version

### ISSUE THREAD

**Issue by ghost** [mohamicorp/search-for-stash-issues#44]
Hello Developers,

I use Bitbucket Server in the very latest version under CentOS 7.3. Unfortunately this add-on can not be activated.

It is displayed, I must look in the logs because of error messages.

Can you confirm that the addon works on Linux?

Thanks in advance.

**Comment by mdavoodi** [comment]
Looked at the logs sent to support, your git version is too low. Updating will fix this issue.
